export const brandAliases: Record<string, string[]> = {
  aeg: ['aeg', 'аег'],
  asko: ['asko', 'аско'],
  beko: ['beko', 'беко'],
  'bone crusher': ['bone crusher', 'bonecrusher', 'бон крашер', 'боун крашер'],
  bosch: ['bosch', 'bosh', 'boshch', 'бош', 'бошь'],
  brandt: ['brandt', 'брандт'],
  candy: ['candy', 'канди'],
  'de dietrich': ['de dietrich', 'dediétrich', 'de-dietrich', 'де дитрих', 'дедиетрих'],
  delonghi: ['delonghi', 'de longhi', 'de-longhi', 'делонги', 'де лонги'],
  dunavox: ['dunavox', 'дунавокс'],
  electrolux: ['electrolux', 'электролюкс'],
  elica: ['elica', 'элика'],
  elikor: ['elikor', 'эликор'],
  evelux: ['evelux', 'эvelux', 'эвелюкс'],
  faber: ['faber', 'фабер'],
  falmec: ['falmec', 'фалмек'],
  franke: ['franke', 'франке'],
  gorenje: ['gorenje', 'горенье', 'горение'],
  granfest: ['granfest', 'гранфест'],
  graude: ['graude', 'грауде'],
  grundig: ['grundig', 'грундиг'],
  haier: ['haier', 'хайер'],
  hebermann: ['hebermann', 'хеберман'],
  hiberg: ['hiberg', 'хайберг', 'хиберг'],
  hitachi: ['hitachi', 'хитачи'],
  hotpoint: ['hotpoint', 'хотпоинт', 'hot point'],
  indesit: ['indesit', 'индезит'],
  "jacky's": ["jacky's", 'jackys', 'jacky', 'джакис', 'джеккис'],
  korting: ['korting', 'кертинг', 'кортинг'],
  krona: ['krona', 'крона'],
  kuppersberg: ['kuppersberg', 'купперсберг', 'куперсберг'],
  kuppersbusch: ['kuppersbusch', 'купперсбуш', 'купперсбушь', 'куперсбуш'],
  lex: ['lex', 'лекс'],
  liebherr: ['liebherr', 'либхер', 'либер'],
  maunfeld: ['maunfeld', 'маунфелд', 'маунфельд'],
  meyvel: ['meyvel', 'мейвел'],
  midea: ['midea', 'мидеа'],
  miele: ['miele', 'миеле'],
  millen: ['millen', 'миллен'],
  monsher: ['monsher', 'моншер'],
  neff: ['neff', 'нефф'],
  omoikiri: ['omoikiri', 'омойкири'],
  rivelato: ['rivelato', 'ривелато'],
  'schaub lorenz': ['schaub lorenz', 'schaublorenz', 'шауб лоренц', 'шоб лоренц'],
  schulthess: ['schulthess', 'шультесс'],
  seaman: ['seaman', 'симан', 'сеаман'],
  siemens: ['siemens', 'сименс'],
  smeg: ['smeg', 'смег'],
  teka: ['teka', 'тека']
};

export const brandCanonicalNames: Record<string, string> = {
  aeg: 'AEG',
  asko: 'ASKO',
  beko: 'BEKO',
  'bone crusher': 'Bone Crusher',
  bosch: 'BOSCH',
  brandt: 'Brandt',
  candy: 'CANDY',
  'de dietrich': 'De Dietrich',
  delonghi: 'DeLonghi',
  dunavox: 'Dunavox',
  electrolux: 'Electrolux',
  elica: 'ELICA',
  elikor: 'Elikor',
  evelux: 'Evelux',
  faber: 'FABER',
  falmec: 'FALMEC',
  franke: 'Franke',
  gorenje: 'GORENJE',
  granfest: 'GranFest',
  graude: 'GRAUDE',
  grundig: 'Grundig',
  haier: 'Haier',
  hebermann: 'Hebermann',
  hiberg: 'HIBERG',
  hitachi: 'Hitachi',
  hotpoint: 'Hotpoint',
  indesit: 'INDESIT',
  "jacky's": "Jacky's",
  korting: 'KORTING',
  krona: 'KRONA',
  kuppersberg: 'Kuppersberg',
  kuppersbusch: 'KUPPERSBUSCH',
  lex: 'LEX',
  liebherr: 'LIEBHERR',
  maunfeld: 'Maunfeld',
  meyvel: 'Meyvel',
  midea: 'Midea',
  miele: 'MIELE',
  millen: 'MILLEN',
  monsher: 'Monsher',
  neff: 'NEFF',
  omoikiri: 'Omoikiri',
  rivelato: 'Rivelato',
  'schaub lorenz': 'Schaub Lorenz',
  schulthess: 'Schulthess',
  seaman: 'SEAMAN',
  siemens: 'SIEMENS',
  smeg: 'SMEG',
  teka: 'Teka'
};
